version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
  backend:
    build:
      context: .
    ports:
      - 5000:5000
    depends_on:
      - mongodb
volumes:
  mongo_data:
